export { HistoriaComponent} from './historia/historia.component';
export { BannerComponent } from  './banner/banner.component';
export { PeliculasComponent } from  './peliculas/peliculas.component';
export { PersonasComponent } from  './personas/personas.component';
export { PlanetasComponent } from  './planetas/planetas.component';
export { EspeciesComponent } from  './especies/especies.component';
export { NavesEspacialesComponent } from  './naves-espaciales/naves-espaciales.component';
export { VehiculosComponent } from  './vehiculos/vehiculos.component';
export { IntegrantesDeTrabajoComponent } from  './integrantes-de-trabajo/integrantes-de-trabajo.component';
export { FooterComponent  } from './footer/footer.component';
